language: python
sudo: false
dist: bionic
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy2"
 - "pypy3"

install:
 - "pip install -U --upgrade-strategy eager pip setuptools wheel"
 - "pip install -U --upgrade-strategy eager -r requirements.txt"
 - "pip install ."

script:
  - "pytest --cov datecond --cov-report term-missing tests/"

notifications:
  email:
    on_success: change
    on_failure: always
