language: python
sudo: false
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy"

install:
 - "pip install -U --update-strategy=eager pip setuptools wheel"
 - "pip install -U --update-strategy=eager -r requirements.txt"
 - "pip install ."

script:
  - "pytest --cov datecond --cov-report term-missing tests/"

notifications:
  email:
    on_success: change
    on_failure: always
